kind: ConfigMap
apiVersion: v1
metadata:
  name: flexvolume-config
  namespace: kube-system
data:
  auth-url: "https://${SERVICE_HOST}/identity_admin/v2.0"
  username: "admin"
  password: "${ADMIN_PASSWORD}"
  tenant-name: "admin"
  region: "RegionOne"
  keyring: "${KEYRING}"